GET http://localhost/api/products-management/products

###

GET http://localhost/api/products-management/products/0

###

POST http://localhost/api/products-management/products/
Content-Type: application/json
{
  "id" : 1,
  "name": "Вакцина от COVID-19",
  "price": 1000000000,
  "description": "Пока не придумали"
}

###

DELETE http://localhost/api/products-management/products/0

###

POST http://localhost/api/sms-management/sms/send?phone=79506658511
Content-Type: application/json

{
  "text": "Hello"
}

###
